openapi: '3.0.2'
components:
  schemas:
    Amenity:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: id
        name:
          type: string
          description: name
      example:
        id: 69
        name: test
